info:
  app:
    name: VaccineCampaign
    description: LA Vaccine Campaign System

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaccine-la
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  error:
    include-stacktrace: never
    include-message: always

